In [1]:
import pandas as pd
import numpy as np
from astropy.coordinates import SkyCoord
import astropy.units as u
roots_tfm = '/home/julien/Documents/Etudes/Astrofisica/Master/TFM/Data'

In [2]:
df_entries_uvot = pd.read_csv(roots_tfm +'/Swift-UVOT/Entries_UVOT_galaxies.csv')
df_entries_om = pd.read_csv(roots_tfm +'/XMM-Newton/Entries_OM_galaxies.csv')
df_entries_galex = pd.read_csv(roots_tfm+'/Galex/Entries_Galex_Galaxies.csv')
df_sources = pd.read_csv(roots_tfm +'/SOURCE_complete_galaxies.csv')
df_sources.head()

,SRCNUM_CUV,SRCNUM_OM,SRCNUM_UVOT,RA,DEC,POSERR,COUNT,W1mag,W2mag,logM
0,0,0,5,0.001106,-40.113253,0.477914,1,18.319859,19.253110,9.633047
1,1,0,10,0.004393,8.250327,0.318405,1,18.694110,18.540552,9.492051
2,2,0,17,0.008504,8.360581,0.332229,1,18.765518,19.116037,10.071917
3,3,0,22,0.010610,8.298201,0.340089,1,15.159580,15.785906,10.650148
4,4,0,30,0.013978,8.190792,0.349532,1,20.946735,21.870068,9.566999

In [3]:
df_sources[df_sources['SRCNUM_OM']== 3298282]

,SRCNUM_CUV,SRCNUM_OM,SRCNUM_UVOT,RA,DEC,POSERR,COUNT,W1mag,W2mag,logM
455440,455440,3298282,0,192.063446,17.774125,0.549904,13,15.629795,16.218868,9.6777

In [4]:
df_test = pd.read_csv(roots_tfm+'/Galex/GUVCat_AIS_FOV055_glat80_00N__85_00N_extract_match_best_8ERR.csv')
df_test[df_test['SRCNUM_OM']== 3298282]

,objid,ra_1,dec_1,glon,glat,tilenum,img,subvisit,fuv_flux,fuv_fluxerr,nuv_flux,nuv_fluxerr,SRCNUM_CUV,SRCNUM_OM,SRCNUM_UVOT,RA_2,DEC_2,POSERR,COUNT,Separation
2587,6378761888717607197,192.0634,17.773017,298.27847,80.61599,50223,545,17,-999.0,-999.0,92.197701,5.092167,455440,3298282,0,192.063446,17.774125,0.549904,13,0.907512

In [5]:
df_test[df_test['SRCNUM_OM']== 3298282]['ra_1'].values*u.deg

In [6]:
c1=SkyCoord(ra=df_test[df_test['SRCNUM_OM']== 3298282]['ra_1'].values*u.deg, dec=df_test[df_test['SRCNUM_OM']== 3298282]['dec_1'].values*u.deg, frame='icrs')
c2=SkyCoord(ra=df_test[df_test['SRCNUM_OM']== 3298282]['RA_2'].values*u.deg, dec=df_test[df_test['SRCNUM_OM']== 3298282]['DEC_2'].values*u.deg, frame='icrs')
c1.separation(c2)

In [7]:
df_entries_galex[df_entries_galex['SRCNUM_CUV'] == 455440]

,SRCNUM_CUV,SRCNUM_GALEX,NUV_UVW2_FLUX,NUV_UVW2_FLUX_ERR,FUV_UVW2_FLUX,FUV_UVW2_FLUX_ERR,NUV_UVM2_FLUX,NUV_UVM2_FLUX_ERR,FUV_UVM2_FLUX,FUV_UVM2_FLUX_ERR,NUV_UVW1_FLUX,NUV_UVW1_FLUX_ERR,FUV_UVW1_FLUX,FUV_UVW1_FLUX_ERR
221263,455440,6378761888717607197,3.546157e-16,1.452431e-17,NaN,NaN,3.192587e-16,1.530874e-17,NaN,NaN,3.795770e-16,2.541072e-17,NaN,NaN

In [8]:
df_sources[df_sources['COUNT']>2].shape[0]

93568

In [9]:
df_entries_om.head()

,SRCNUM,UVW2_FLUX,UVW2_FLUX_ERR,UVM2_FLUX,UVM2_FLUX_ERR,UVW1_FLUX,UVW1_FLUX_ERR,U_FLUX,U_FLUX_ERR,B_FLUX,...,B_QUALITY_FLAG,V_QUALITY_FLAG,UVW2_EXTENDED,UVM2_EXTENDED,UVW1_EXTENDED,U_EXTENDED,B_EXTENDED,V_EXTENDED,MJD,OBSID
0,16,NaN,NaN,NaN,NaN,3.560710e-17,5.060595e-18,3.203722e-17,4.149678e-18,NaN,...,999,999,NaN,NaN,True,True,NaN,NaN,58972,862640901
1,17,NaN,NaN,NaN,NaN,NaN,NaN,3.356253e-17,4.603683e-18,NaN,...,999,999,NaN,NaN,NaN,True,NaN,NaN,58972,862640901
2,70,NaN,NaN,9.101157e-17,1.539409e-17,4.898313e-17,4.990574e-18,NaN,NaN,NaN,...,999,999,NaN,False,False,NaN,NaN,NaN,59205,864053501
3,100,NaN,NaN,NaN,NaN,1.583518e-17,4.226986e-18,NaN,NaN,NaN,...,999,999,NaN,NaN,False,NaN,NaN,NaN,59205,864053501
4,120,NaN,NaN,NaN,NaN,3.006780e-17,3.924584e-18,2.040174e-17,3.653935e-18,NaN,...,999,999,NaN,NaN,False,False,NaN,NaN,53534,302580501

In [10]:
#df_sources = df_sources[df_sources['COUNT']>2]

In [11]:
#df_entries_uvot = df_sources.merge(df_entries_uvot,left_on='SRCNUM_UVOT',right_on='SRCNUM').merge(df_entries_galex,on='SRCNUM_CUV',how='left').drop({'SRCNUM'},axis=1)
df_entries_uvot = df_sources.merge(df_entries_uvot,left_on='SRCNUM_UVOT',right_on='SRCNUM').drop({'SRCNUM'},axis=1)
df_entries_uvot = df_entries_uvot.loc[:, ~df_entries_uvot.columns.str.contains('^Unnamed')]
df_entries_uvot['CAT'] = 'UVOT'

In [12]:
df_entries_uvot.head()
df_entries_uvot.columns.values

array(['SRCNUM_CUV', 'SRCNUM_OM', 'SRCNUM_UVOT', 'RA', 'DEC', 'POSERR',
       'COUNT', 'W1mag', 'W2mag', 'logM', 'UVW2_FLUX', 'UVW2_FLUX_ERR',
       'UVM2_FLUX', 'UVM2_FLUX_ERR', 'UVW1_FLUX', 'UVW1_FLUX_ERR',
       'U_FLUX', 'U_FLUX_ERR', 'B_FLUX', 'B_FLUX_ERR', 'V_FLUX',
       'V_FLUX_ERR', 'UVW2_QUALITY_FLAG', 'UVM2_QUALITY_FLAG',
       'UVW1_QUALITY_FLAG', 'U_QUALITY_FLAG', 'B_QUALITY_FLAG',
       'V_QUALITY_FLAG', 'UVW2_EXTENDED', 'UVM2_EXTENDED',
       'UVW1_EXTENDED', 'U_EXTENDED', 'B_EXTENDED', 'V_EXTENDED', 'MJD',
       'OBSID', 'CAT'], dtype=object)

In [13]:
#df_entries_om = df_sources.merge(df_entries_om,left_on='SRCNUM_OM',right_on='SRCNUM').merge(df_entries_galex,on='SRCNUM_CUV',how='left').drop({'SRCNUM'},axis=1)
df_entries_om = df_sources.merge(df_entries_om,left_on='SRCNUM_OM',right_on='SRCNUM').drop({'SRCNUM'},axis=1)
df_entries_om = df_entries_om.loc[:, ~df_entries_om.columns.str.contains('^Unnamed')]
df_entries_om['CAT'] = 'OM'

In [14]:
df_entries_galex = df_sources.merge(df_entries_galex,on='SRCNUM_CUV')

In [15]:
from pandas.api.types import CategoricalDtype
cat_type = CategoricalDtype(categories=["True","False","<NA>"], ordered=False)
df_entries_galex_NUV = df_entries_galex[['SRCNUM_CUV','SRCNUM_OM','SRCNUM_UVOT','RA', 'DEC','POSERR','COUNT','W1mag', 'W2mag', 'logM',\
                                         'NUV_UVW2_FLUX','NUV_UVW2_FLUX_ERR','NUV_UVM2_FLUX', 'NUV_UVM2_FLUX_ERR','NUV_UVW1_FLUX', \
                                         'NUV_UVW1_FLUX_ERR','SRCNUM_GALEX']].rename(columns={'NUV_UVW2_FLUX':'UVW2_FLUX',\
                                                                                              'NUV_UVW2_FLUX_ERR':'UVW2_FLUX_ERR',\
                                                                          'NUV_UVM2_FLUX':'UVM2_FLUX','NUV_UVM2_FLUX_ERR':'UVM2_FLUX_ERR',\
                                                                          'NUV_UVW1_FLUX':'UVW1_FLUX','NUV_UVW1_FLUX_ERR':'UVW1_FLUX_ERR',\
                                                                          'SRCNUM_GALEX':'OBSID'})
df_entries_galex_FUV=df_entries_galex[['SRCNUM_CUV','SRCNUM_OM','SRCNUM_UVOT','RA', 'DEC','POSERR','COUNT','W1mag', 'W2mag', 'logM',\
                                       'FUV_UVW2_FLUX','FUV_UVW2_FLUX_ERR','FUV_UVM2_FLUX', 'FUV_UVM2_FLUX_ERR','FUV_UVW1_FLUX', \
                                       'FUV_UVW1_FLUX_ERR', 'SRCNUM_GALEX']].rename(columns={'FUV_UVW2_FLUX':'UVW2_FLUX',\
                                                                                             'FUV_UVW2_FLUX_ERR':'UVW2_FLUX_ERR',\
                                                                          'FUV_UVM2_FLUX':'UVM2_FLUX','FUV_UVM2_FLUX_ERR':'UVM2_FLUX_ERR',\
                                                                          'FUV_UVW1_FLUX':'UVW1_FLUX','FUV_UVW1_FLUX_ERR':'UVW1_FLUX_ERR',\
                                                                          'SRCNUM_GALEX':'OBSID'})
for name in ['U_FLUX','U_FLUX_ERR', 'B_FLUX', 'B_FLUX_ERR', 'V_FLUX', 'V_FLUX_ERR']:
    df_entries_galex_NUV[name] = np.nan
    df_entries_galex_FUV[name] = np.nan

for name in ['UVW2_QUALITY_FLAG', 'UVM2_QUALITY_FLAG','UVW1_QUALITY_FLAG','U_QUALITY_FLAG', 'B_QUALITY_FLAG', 'V_QUALITY_FLAG']:
    df_entries_galex_NUV[name] = 0
    df_entries_galex_FUV[name] = 0
    
for name in ['UVW2_EXTENDED', 'UVM2_EXTENDED', 'UVW1_EXTENDED', 'U_EXTENDED','B_EXTENDED', 'V_EXTENDED']:
    df_entries_galex_NUV[name] = "<NA>"
    df_entries_galex_NUV[name] = df_entries_galex_NUV[name].astype(cat_type)
    df_entries_galex_FUV[name] = "<NA>"
    df_entries_galex_FUV[name] = df_entries_galex_FUV[name].astype(cat_type)

df_entries_galex_NUV['MJD'] = 54466
df_entries_galex_FUV['MJD'] = 54466
df_entries_galex_NUV['CAT'] = 'GALEX_NUV'
df_entries_galex_FUV['CAT'] = 'GALEX_FUV'

In [16]:
df_entries_galex = pd.concat([df_entries_galex_NUV,df_entries_galex_FUV])

In [17]:
df_entries_galex= df_entries_galex[list(df_entries_om.columns.values)]

In [18]:
df_sources_UV_galex = df_entries_galex.groupby('SRCNUM_CUV').agg({'SRCNUM_CUV':'first'})
df_sources_UV_galex.shape[0]

232554

In [19]:
df_entries = pd.concat([df_entries_om,df_entries_uvot])
df_sources_UV = df_entries.groupby('SRCNUM_CUV').agg({'SRCNUM_CUV':'first'})
df_sources_UV.shape[0]

585477

In [20]:
df_entries = pd.concat([df_entries_om,df_entries_uvot]).dropna(subset=['UVW1_FLUX','UVM2_FLUX','UVW2_FLUX'], how='all')
df_sources_UV = df_entries.groupby('SRCNUM_CUV').agg({'SRCNUM_CUV':'first'})
df_sources_UV.shape[0]

429574

In [21]:
df_entries = pd.concat([df_entries_om,df_entries_uvot,df_entries_galex])
#df_entries = pd.concat([df_entries_om,df_entries_uvot])
df_entries.sort_values('SRCNUM_CUV').reset_index(drop=True)
df_entries.shape

(1681959, 37)

In [22]:
df_entries.dtypes

SRCNUM_CUV             int64
SRCNUM_OM              int64
SRCNUM_UVOT            int64
RA                   float64
DEC                  float64
POSERR               float64
COUNT                  int64
W1mag                float64
W2mag                float64
logM                 float64
UVW2_FLUX            float64
UVW2_FLUX_ERR        float64
UVM2_FLUX            float64
UVM2_FLUX_ERR        float64
UVW1_FLUX            float64
UVW1_FLUX_ERR        float64
U_FLUX               float64
U_FLUX_ERR           float64
B_FLUX               float64
B_FLUX_ERR           float64
V_FLUX               float64
V_FLUX_ERR           float64
UVW2_QUALITY_FLAG      int64
UVM2_QUALITY_FLAG      int64
UVW1_QUALITY_FLAG      int64
U_QUALITY_FLAG         int64
B_QUALITY_FLAG         int64
V_QUALITY_FLAG         int64
UVW2_EXTENDED         object
UVM2_EXTENDED         object
UVW1_EXTENDED         object
U_EXTENDED            object
B_EXTENDED            object
V_EXTENDED            object
MJD                    int64
OBSID                  int64
CAT                   object
dtype: object

In [24]:
df_entries.to_csv(roots_tfm+'/Entries_galaxies_more_than_2.csv',index=False)