In [1]:
import pandas as pd
import numpy as np
roots_tfm = '/home/julien/Documents/Etudes/Astrofisica/Master/TFM/Data'

In [2]:
df_entries_uvot = pd.read_csv(roots_tfm +'/Swift-UVOT/Entries_UVOT_galaxies.csv')
df_entries_om = pd.read_csv(roots_tfm +'/XMM-Newton/Entries_OM_galaxies.csv')
df_entries_galex = pd.read_csv(roots_tfm+'/Galex/Entries_Galex_Galaxies.csv')
df_sources = pd.read_csv(roots_tfm +'/SOURCE_complete_galaxies.csv')
df_sources.head()

   SRCNUM_CUV  SRCNUM_OM  SRCNUM_UVOT        RA        DEC    POSERR  COUNT
0           0          0            5  0.001106 -40.113253  0.477914      1
1           1          0           10  0.004393   8.250327  0.318405      1
2           2          0           17  0.008504   8.360581  0.332229      1
3           3          0           22  0.010610   8.298201  0.340089      1
4           4          0           30  0.013978   8.190792  0.349532      1

In [3]:
df_sources[df_sources['COUNT']>2].shape[0]

93568

In [4]:
df_entries_om.head()

,SRCNUM,UVW2_FLUX,UVW2_FLUX_ERR,UVM2_FLUX,UVM2_FLUX_ERR,UVW1_FLUX,UVW1_FLUX_ERR,U_FLUX,U_FLUX_ERR,B_FLUX,...,B_QUALITY_FLAG,V_QUALITY_FLAG,UVW2_EXTENDED,UVM2_EXTENDED,UVW1_EXTENDED,U_EXTENDED,B_EXTENDED,V_EXTENDED,MJD,OBSID
0,16,NaN,NaN,NaN,NaN,3.560710e-17,5.060595e-18,3.203722e-17,4.149678e-18,NaN,...,999,999,NaN,NaN,True,True,NaN,NaN,58972,862640901
1,17,NaN,NaN,NaN,NaN,NaN,NaN,3.356253e-17,4.603683e-18,NaN,...,999,999,NaN,NaN,NaN,True,NaN,NaN,58972,862640901
2,70,NaN,NaN,9.101157e-17,1.539409e-17,4.898313e-17,4.990574e-18,NaN,NaN,NaN,...,999,999,NaN,False,False,NaN,NaN,NaN,59205,864053501
3,100,NaN,NaN,NaN,NaN,1.583518e-17,4.226986e-18,NaN,NaN,NaN,...,999,999,NaN,NaN,False,NaN,NaN,NaN,59205,864053501
4,120,NaN,NaN,NaN,NaN,3.006780e-17,3.924584e-18,2.040174e-17,3.653935e-18,NaN,...,999,999,NaN,NaN,False,False,NaN,NaN,53534,302580501

In [5]:
df_sources = df_sources[df_sources['COUNT']>2]

In [6]:
df_entries_uvot = df_sources.merge(df_entries_uvot,left_on='SRCNUM_UVOT',right_on='SRCNUM').merge(df_entries_galex,on='SRCNUM_CUV',how='left').drop({'SRCNUM'},axis=1)
df_entries_uvot = df_entries_uvot.loc[:, ~df_entries_uvot.columns.str.contains('^Unnamed')]
df_entries_uvot['CAT'] = 'UVOT'

In [7]:
df_entries_uvot.head()

,SRCNUM_CUV,SRCNUM_OM,SRCNUM_UVOT,RA,DEC,POSERR,COUNT,UVW2_FLUX,UVW2_FLUX_ERR,UVM2_FLUX,...,FUV_UVW2_FLUX_ERR,NUV_UVM2_FLUX,NUV_UVM2_FLUX_ERR,FUV_UVM2_FLUX,FUV_UVM2_FLUX_ERR,NUV_UVW1_FLUX,NUV_UVW1_FLUX_ERR,FUV_UVW1_FLUX,FUV_UVW1_FLUX_ERR,CAT
0,36,0,268,0.088921,-76.934918,0.363814,4,NaN,NaN,7.559767e-17,...,7.174444e-17,7.884226e-17,3.205446e-17,8.295794e-17,4.631456e-17,5.802137e-17,1.918094e-17,5.941777e-17,2.736658e-17,UVOT
1,36,0,268,0.088921,-76.934918,0.363814,4,NaN,NaN,NaN,...,7.174444e-17,7.884226e-17,3.205446e-17,8.295794e-17,4.631456e-17,5.802137e-17,1.918094e-17,5.941777e-17,2.736658e-17,UVOT
2,36,0,268,0.088921,-76.934918,0.363814,4,NaN,NaN,NaN,...,7.174444e-17,7.884226e-17,3.205446e-17,8.295794e-17,4.631456e-17,5.802137e-17,1.918094e-17,5.941777e-17,2.736658e-17,UVOT
3,36,0,268,0.088921,-76.934918,0.363814,4,1.170202e-16,4.532768e-18,4.435516e-17,...,7.174444e-17,7.884226e-17,3.205446e-17,8.295794e-17,4.631456e-17,5.802137e-17,1.918094e-17,5.941777e-17,2.736658e-17,UVOT
4,87,0,616,0.191412,-76.880424,0.274232,3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UVOT

In [8]:
df_entries_om = df_sources.merge(df_entries_om,left_on='SRCNUM_OM',right_on='SRCNUM').merge(df_entries_galex,on='SRCNUM_CUV',how='left').drop({'SRCNUM'},axis=1)
df_entries_om = df_entries_om.loc[:, ~df_entries_om.columns.str.contains('^Unnamed')]
df_entries_om['CAT'] = 'OM'

In [9]:
df_entries = pd.concat([df_entries_om,df_entries_uvot])
df_entries.sort_values('SRCNUM_CUV').reset_index(drop=True)
df_entries.shape

(629996, 47)

In [10]:
df_entries.dtypes

SRCNUM_CUV             int64
SRCNUM_OM              int64
SRCNUM_UVOT            int64
RA                   float64
DEC                  float64
POSERR               float64
COUNT                  int64
UVW2_FLUX            float64
UVW2_FLUX_ERR        float64
UVM2_FLUX            float64
UVM2_FLUX_ERR        float64
UVW1_FLUX            float64
UVW1_FLUX_ERR        float64
U_FLUX               float64
U_FLUX_ERR           float64
B_FLUX               float64
B_FLUX_ERR           float64
V_FLUX               float64
V_FLUX_ERR           float64
UVW2_QUALITY_FLAG      int64
UVM2_QUALITY_FLAG      int64
UVW1_QUALITY_FLAG      int64
U_QUALITY_FLAG         int64
B_QUALITY_FLAG         int64
V_QUALITY_FLAG         int64
UVW2_EXTENDED         object
UVM2_EXTENDED         object
UVW1_EXTENDED         object
U_EXTENDED            object
B_EXTENDED            object
V_EXTENDED            object
MJD                    int64
OBSID                  int64
SRCNUM_GALEX         float64
NUV_UVW2_FLUX        float64
NUV_UVW2_FLUX_ERR    float64
FUV_UVW2_FLUX        float64
FUV_UVW2_FLUX_ERR    float64
NUV_UVM2_FLUX        float64
NUV_UVM2_FLUX_ERR    float64
FUV_UVM2_FLUX        float64
FUV_UVM2_FLUX_ERR    float64
NUV_UVW1_FLUX        float64
NUV_UVW1_FLUX_ERR    float64
FUV_UVW1_FLUX        float64
FUV_UVW1_FLUX_ERR    float64
CAT                   object
dtype: object

In [11]:
(df_entries['SRCNUM_GALEX']==np.nan).any()

np.False_

In [12]:
df_entries.to_csv(roots_tfm+'/Entries_galaxies_more_than_2.csv',index=False)